### ISSUE TITLE
Uncaught Error: Could not find module

### ISSUE THREAD

**Issue by wooandoo** [winding-lines/ember-cli-typify#6]
Hello,

I tried this plugin with a very simple code:

in app/controller/application.js:
```js
import Ember from 'ember';

import MessageBuilder from '../lib/message-builder';

export default Ember.Controller.extend({
  message: 'pending...',

  init() {
    let builder = new MessageBuilder();
    this.set('message', builder.build('world'));
  }
});
```

and in app/lib/message-builder.ts:
```js
export default class MessageBuilder {
  build(name: string) {
    console.log('build '+name);
    return `hello ${name}`
  }
}
```

compilation is OK
if a update any file, I see the compilation of the file: OK

but the typescript file isn't exported int the JS project sources, and so I have an error
> Uncaught Error: Could not find module `demo-ember-typescript/lib/message-builder` imported from `demo-ember-typescript/controllers/application`(…)

thanks for your help

Frédéric

**Comment by winding-lines** [comment]
Frédéric

Members of the Ember community reached out to me and asked me to merge this code in the pre-existing ember-cli-typescript. Do you mind switching to ember-cli-typescript and let me know if you still see this problem? Please file a new issue agains that addon if you do.

Thanks a lot of your patience and help to make the community better.

Marius
